<?php
namespace app\admin\common;

use think\Controller;
use think\Request;
use think\Session;

class Base extends \think\Controller
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        
        //在公共控制器的初始化方法中,创建一个常量用来判断用户是否登录或已登录
        define('USER_ID', Session::get('user_id','Admin'));
        
        //如果登录常量为NULL,表示没有登录
        if (is_null(USER_ID)) {
            $this -> error('未登录,无权访问~~', 'Login/login');
        }
     
    }
    
}
